### ISSUE TITLE
Avoid GitHub dependency

### ISSUE THREAD

**Issue by Jack-Works** [i18next/i18next-translation-parser#11]
https://github.com/i18next/i18next-translation-parser/blob/616b443e94113633a41383ae233b5b6bf3af583d/package.json#L18

Can you find some dependency on the npm? thanks!

**Comment by adrai** [comment]
this is a normal dependency, but pointing to github and not to npm

**Comment by Jack-Works** [comment]
> this is a normal dependency, but pointing to github and not to npm

yeah I know that, but it does not be pinned to a specific version and might break in the future

**Comment by adrai** [comment]
has not changed since years...
and we control that repo, so no problem
